# Generated by Django 3.2.7 on 2021-10-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211004_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_song',
        ),
    ]
